"use client"

import { useEffect, useState } from "react"

interface MailItem {
  to: string
  subject: string
  html: string
  date: string
}

// Browser inbox for the captured-email mailbox (API /dev/mail/list, reached via the
// same-origin /api proxy). Replaces the Mailhog UI on the deploy, where Mailhog can't
// receive mail. Public route (see proxy.ts), auto-refreshes so codes appear quickly.
export default function InboxPage() {
  const [items, setItems] = useState<MailItem[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(false)

  useEffect(() => {
    let active = true
    async function load() {
      try {
        const res = await fetch("/api/dev/mail/list", { cache: "no-store" })
        const data = await res.json()
        if (active) {
          setItems(data?.data?.items ?? [])
          setError(false)
        }
      } catch {
        if (active) setError(true)
      } finally {
        if (active) setLoading(false)
      }
    }
    load()
    const t = setInterval(load, 3000)
    return () => {
      active = false
      clearInterval(t)
    }
  }, [])

  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border px-6 py-4">
        <h1 className="text-lg font-bold tracking-tight">Sealio Inbox</h1>
        <p className="mt-0.5 text-sm text-foreground-muted">
          Captured emails — verification codes &amp; signing invites. Auto-refreshes every 3s.
        </p>
      </header>

      <main className="mx-auto max-w-3xl space-y-3 px-4 py-6">
        {loading && <p className="text-sm text-foreground-muted">Loading…</p>}
        {!loading && error && <p className="text-sm text-red-500">Could not load the inbox.</p>}
        {!loading && !error && items.length === 0 && (
          <p className="text-sm text-foreground-muted">
            No emails yet. Send a document to a signer, then watch this page.
          </p>
        )}
        {items.map((m, i) => (
          <article key={i} className="rounded-lg border border-border bg-surface p-4">
            <div className="flex items-baseline justify-between gap-3">
              <h2 className="font-semibold">{m.subject}</h2>
              <time className="shrink-0 text-xs text-foreground-subtle">
                {new Date(m.date).toLocaleString()}
              </time>
            </div>
            <p className="mt-0.5 text-xs text-foreground-muted">To: {m.to}</p>
            {/* Email HTML is generated by our own API (trusted), rendered on white like a mail client. */}
            <div
              className="mt-3 overflow-x-auto rounded-md bg-white p-3 text-sm text-black"
              dangerouslySetInnerHTML={{ __html: m.html }}
            />
          </article>
        ))}
      </main>
    </div>
  )
}
